name: Sync Issue to Azure DevOps work item

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Adding work item in azure
    steps:       
    - uses: danhellem/github-actions-issue-to-work-item@master
      env:     
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: 'scaniadigitaldesignsystem'
        ado_project: 'sdds'
        ado_wit: 'Task'
        ado_new_state: 'New'
        ado_close_state: 'Done'
        ado_active_state: 'Doing'
